Add linter for the JavaScript port
MattIPv4/do_username pull request #19
Opened 2020-10-26 13:35 UTC by sudiptog81

### Summary

* Added a linter for the JS port to enforce code style and code consistency.
* Added scripts to check and fix linter issues.

Closes #16.

2020-10-26 13:37 UTC, MattIPv4 requested changes

2020-10-26 13:37 UTC, MattIPv4 commented on javascript/.eslintrc.json
> +}
```suggestion
}

```
newline eof

2020-10-26 13:37 UTC, MattIPv4 commented on javascript/package.json
> +}
```suggestion
}

```
newline eof

2020-10-26 13:40 UTC, sudiptog81 commented on javascript/.eslintrc.json
> +}
VSCode :)

2020-10-26 19:32 UTC, MattIPv4 reviewed
This seems to be setting a huge number of custom rules beyond the default recommended -- are they all needed, I'd prefer to keep our customisations minimal if possible initially?

2020-10-27 00:47 UTC, sudiptog81 commented
I chose the option to inspect the actual file to detect the code style, however, we can definitely keep the configuration minimal by removing the rules key. I'll make the changes.

2020-10-27 09:35 UTC, MattIPv4 requested changes
I'm happy to set some basic rules based on the code style present, but what was present before seemed to be setting absolutely everything, which is rather excessive imo.

```
    "rules": {
        "space-before-function-paren": [
            "error",
            {
                "anonymous": "always",
                "named": "never",
                "asyncArrow": "always"
            }
        ],
        "object-curly-spacing": [
            "error",
            "always"
        ],
        "prefer-const": "error",
        "indent": [
            "error",
            4,
            {
                "SwitchCase": 1
            }
        ],
        "semi": [
            "error",
            "always"
        ],
        "quotes": [
            "error",
            "single",
            {
                "avoidEscape": true
            }
        ],
        "object-curly-newline": [
            "error",
            {
                "multiline": true,
                "consistent": true
            }
        ],
        "comma-dangle": [
            "error",
            "always-multiline"
        ],
        "comma-spacing": [
            "error",
            {
                "before": false,
                "after": true
            }
        ],
        "comma-style": [
            "error",
            "last"
        ],
        "eol-last": "error",
        "key-spacing": [
            "error",
            {
                "beforeColon": false,
                "afterColon": true
            }
        ],
        "keyword-spacing": [
            "error",
            {
                "before": true,
                "after": true
            }
        ],
        "block-spacing": "error",
        "space-in-parens": [
            "error",
            "never"
        ],
        "space-before-blocks": "error",
        "no-trailing-spaces": "error",
        "semi-spacing": [
            "error",
            {
                "before": false,
                "after": true
            }
        ],
        "space-infix-ops": "error",
        "no-empty": "error",
        "max-len": [
            "error",
            {
                "code": 120,
                "ignoreComments": true,
                "ignoreStrings": true,
                "ignoreTemplateLiterals": true,
                "ignoreRegExpLiterals": true
            }
        ]
    }
```

2020-10-27 09:35 UTC, MattIPv4 commented on javascript/.eslintrc.json
> +        "node": true
```suggestion
        "commonjs": true,
        "es6": true
```
We don't need node-specific or browser-specific features at present.

2020-10-27 11:34 UTC, MattIPv4 approved these changes
Lgtm, tyvm!

2020-10-27 11:34 UTC, merged