Add a rust crate
MattIPv4/do_username pull request #21
Opened 2020-10-26 20:49 UTC by ThatCopy

Add a rust crate. I've already published this on crates.io [link](https://crates.io/crates/do_username), but I can transfer ownership.

2020-10-27 09:49 UTC, MattIPv4 requested changes

2020-10-27 09:49 UTC, MattIPv4 commented on .gitignore
> +#Rust crate
```suggestion
# Rust crate
```
Spacing

2020-10-27 09:49 UTC, MattIPv4 commented on .gitignore
> +target
```suggestion
target

```
newline eof

2020-10-27 09:49 UTC, MattIPv4 commented on rust/README.md
> +## Example
```suggestion

## Example
```
newline before heading

2020-10-27 09:49 UTC, MattIPv4 commented on rust/src/lib.rs
> +		descriptors.append(&mut size);
As per the notes in the main README, these should be exported as constants in the module that anyone can access -- they should be frozen/immutable.

2020-10-27 09:49 UTC, MattIPv4 commented on rust/src/lib.rs
> +	pub fn get() -> String {
```suggestion
	pub fn generate(size: Option<usize>) -> String {
	  let max_size = size.unwrap_or(30);
```
Method should be named `generate`, per main README, and should support an optional size param.

2020-10-27 09:49 UTC, MattIPv4 commented on rust/src/lib.rs
> +		if format!("{}{}{}", rand_desc, rand_color, rand_noun).len() <= 30 {
```suggestion
		if format!("{}{}{}", rand_desc, rand_color, rand_noun).len() <= max_size {
```
Use new size param

2020-10-27 09:49 UTC, MattIPv4 commented on rust/src/lib.rs
> +		} else if format!("{}{}", rand_desc, rand_noun).len() <= 30 {
```suggestion
		} else if format!("{}{}", rand_desc, rand_noun).len() <= max_size {
```
Use new size param

2020-10-27 09:49 UTC, MattIPv4 commented on rust/src/lib.rs
> +		} else if format!("{}{}", rand_color, rand_noun).len() <= 30 {
```suggestion
		} else if format!("{}{}", rand_color, rand_noun).len() <= max_size {
```
Use new size param

2020-10-27 09:49 UTC, MattIPv4 commented on rust/src/lib.rs
> +			return up_format(vec![rand_noun])
```suggestion
			return up_format(vec![rand_noun])[..max_size]
```
Needs to be sliced to the maximum size

2020-10-27 09:49 UTC, MattIPv4 commented on rust/src/lib.rs
> +}
```suggestion
}

```
newline eof

2020-10-27 11:28 UTC, ThatCopy commented
I have made the changes, only thing I could not fix is the public sea_list and descriptors. I couldn't figure it out, sorry.

2020-10-27 11:47 UTC, MattIPv4 commented
I should note I don't know rust at all -- but, if you have them all as vectors instead of arrays, can you not use something like https://stackoverflow.com/a/56490417/5577674 to build the final two as well?

2020-10-27 11:57 UTC, ThatCopy commented
If I use `let`, works fine, if I switch to `const` it doesn't work. [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b39c5db807bc49b0bfb5256e89af7182)

2020-10-27 12:07 UTC, MattIPv4 commented
Did some more googling, looks like lazy-static lets you achieve this: https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=08081d17d0cb95e59a5008d0eac95c6d

2020-10-27 12:25 UTC, ThatCopy commented
Yup, now its updated.

2020-10-27 17:05 UTC, MattIPv4 requested changes

2020-10-27 17:05 UTC, MattIPv4 commented on .gitignore
>  ruby/coverage
```suggestion
ruby/coverage

# Rust crate
rust/target

```
Add the rust specific items after ruby

2020-10-27 17:05 UTC, MattIPv4 commented on rust/Cargo.toml
> +lazy_static = "1.0.1"
```suggestion
lazy_static = "1.0.1"

```
newline eof

2020-10-27 17:05 UTC, MattIPv4 commented on rust/README.md
> +    println!("{}", do_username::get());
```suggestion
    println!("{}", do_username::generate());
```
Method was renamed

2020-10-27 17:05 UTC, MattIPv4 commented on rust/src/lib.rs
> +		pub static ref SEA_OBJECTS: std::vec::Vec<&'static str> = vec!["boatShip", "submarine", "yacht", "dinghy", "raft", "kelp", "seaweed", "anchor"];
```suggestion
		pub static ref SEA_OBJECTS: std::vec::Vec<&'static str> = vec!["boat", "ship", "submarine", "yacht", "dinghy", "raft", "kelp", "seaweed", "anchor"];
```
String typo

2020-10-27 17:05 UTC, MattIPv4 commented on rust/src/lib.rs
> +		pub static ref SIZE_DESCRIPTORS: std::vec::Vec<&'static str> = vec!["large", "big", "small", "giant", "massive", "tiny", "little", "yuge"];
```suggestion
		pub static ref SIZE_DESCRIPTORS: std::vec::Vec<&'static str> = vec!["large", "big", "small", "giant", "massive", "tiny", "little"];
```
String typo

2020-10-27 17:05 UTC, MattIPv4 commented on rust/src/lib.rs
> +
```suggestion
```
Consistent whitespace

2020-10-27 17:05 UTC, MattIPv4 commented on rust/src/lib.rs
> +	pub fn generate(size: Option<usize>) -> String {
```suggestion

	pub fn generate(size: Option<usize>) -> String {
```
Consistent whitespace

2020-10-27 17:05 UTC, MattIPv4 commented on rust/src/lib.rs
> +	lazy_static! {
```suggestion

	lazy_static! {
```
Consistent whitespace

2020-10-27 17:05 UTC, MattIPv4 commented on rust/src/lib.rs
> +	fn up_format(arr: Vec<&str>) -> String {
```suggestion

	fn up_format(arr: Vec<&str>) -> String {
```
Consistent whitespace

2020-10-27 17:05 UTC, MattIPv4 commented on rust/README.md
> +
```suggestion
```
Consistent whitespace

2020-10-27 17:45 UTC, MattIPv4 requested changes
One final code change, we have a mix of `std::vec::Vec` and `Vec`. I think we're safe to just use `Vec` everywhere?

2020-10-27 18:30 UTC, ThatCopy commented
AFAIK they are the same

2020-10-27 18:36 UTC, ThatCopy commented
Almost forgot, do you want me to add you to the `authors` in `Cargo.toml` if yes, can you give me the email I should use?

2020-10-28 15:07 UTC, MattIPv4 commented
Yeah, please add `DigialOcean, Matt Cowley <me@mattcowley.co.uk>` to authors :)

2020-10-28 15:44 UTC, MattIPv4 commented
👋 One final thing, could you add a quick file on how to publish a version for posterity (see https://github.com/MattIPv4/do_username/pull/24)?

2020-10-28 15:59 UTC, MattIPv4 approved these changes
Lgtm!

2020-10-28 16:00 UTC, MattIPv4 commented
Tyvm for porting this over to Rust -- final thing before merging, how do we transfer ownership on crates?

(Once merged I'll do a 1.0.0 release as the changes in this PR involve a public method change from the original crate)

2020-10-28 16:02 UTC, ThatCopy commented
I'm pretty new to this but I think I can add you by a username. You will need to make a crates.io account. 
![image](https://user-images.githubusercontent.com/62877244/97462777-61d64b00-193f-11eb-99a4-db48de95afe7.png)

2020-10-28 16:03 UTC, ThatCopy commented
You will need to make a crates.io account. Than I can add you by your username 
![image](https://user-images.githubusercontent.com/62877244/97462952-8a5e4500-193f-11eb-97dd-619c056237a6.png)

2020-10-28 16:05 UTC, MattIPv4 commented
👍 I'm `MattIPv4` on crates

2020-10-28 16:06 UTC, MattIPv4 commented
Oki, looks like we're good to go. Will merge and attempt the 1.0.0 release. Ty again!

2020-10-28 16:06 UTC, merged