Add a go module
MattIPv4/do_username pull request #29
Opened 2020-10-29 17:29 UTC by ThatCopy

I couldn't make a optional parameter and you can't make a `const `array in go, but 
> An array isn't immutable by nature; you can't make it constant.

2020-10-29 17:39 UTC, ThatCopy commented
I had to use CamelCase, because go its very strict of x-case. I can use kebab-case but go's linting doesn't like that.

2020-10-30 11:41 UTC, MattIPv4 requested changes

2020-10-30 11:41 UTC, MattIPv4 commented on go/dousername.go
> +func randomDesc(seaCreaturess []string, randNoun string, descriptors []string, verbs []string) string {
Why do we pass in `seaCreaturess`, `descriptors` and `verbs` here? Can we just not use the arrays directly?

2020-10-30 11:41 UTC, MattIPv4 commented on go/dousername.go
> +	} else if len(randDesc+randColor) <= 30 {
```suggestion
	} else if len(randDesc+randNoun) <= 30 {
```

2020-10-30 11:41 UTC, MattIPv4 commented on go/dousername.go
> +		return capitalize([]string{randDesc, randColor})
```suggestion
		return capitalize([]string{randDesc, randNoun})
```

2020-10-30 11:41 UTC, MattIPv4 commented on go/dousername.go
> +		return capitalize([]string{randColor, randColor})
```suggestion
		return capitalize([]string{randColor, randNoun})
```

2020-10-30 11:41 UTC, MattIPv4 commented on go/dousername.go
> +		return capitalize([]string{randNoun})
This needs to be sliced to `30`

2020-10-30 11:41 UTC, MattIPv4 commented on go/go.mod
> +module github.com/ThatCopy/go-do-namegen
This needs updating to point to this repo

2020-10-30 11:41 UTC, MattIPv4 commented on go/README.md
> +	"github.com/ThatCopy/go-do-namegen"
This needs updating to point to this repo

2020-10-30 11:41 UTC, MattIPv4 commented on go/README.md
> +	fmt.Println(dousername.GetName())
```suggestion
	fmt.Println(dousername.Generate())
```

2020-10-30 11:41 UTC, MattIPv4 commented on go/dousername.go
> +func generate() string {
```suggestion
func Generate() string {
```
Needs to be PascalCase to be public iirc

2022-12-16 20:19 UTC, MattIPv4 approved these changes
Sorry for not getting to this sooner, not sure why I lost track of updates here a while back. LGTM, tyvm!

2022-12-16 20:19 UTC, merged